{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toposcope.fullname" . }}-db
  labels:
    {{- include "toposcope.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}
---
{{- if and (eq .Values.auth.mode "api-key") (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toposcope.fullname" . }}-auth
  labels:
    {{- include "toposcope.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.auth.apiKey | quote }}
{{- end }}
---
{{- if and (eq .Values.storage.backend "s3") (not .Values.storage.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toposcope.fullname" . }}-s3
  labels:
    {{- include "toposcope.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.storage.s3.accessKey | quote }}
  secret-key: {{ .Values.storage.s3.secretKey | quote }}
{{- end }}
